### ISSUE TITLE
Failed to download contributors info of the project in Crowdin Enterprise

### ISSUE THREAD

**Issue by hwhsu1231** [andrii-bodnar/action-crowdin-contributors#102]
### Problem Description

Recently, I tried to download contributors info of the project in Crowdin Enterprise:

<details><summary>Click to expand the configuration I used in the workflow</summary>

```yml
      - name: Set up Environment Variables
        shell: bash
        run: |
          echo "CROWDIN_PROJECT_ID=8"                                         >> $GITHUB_ENV
          echo "CROWDIN_ORGANIZATION=https://org-test.api.crowdin.com"        >> $GITHUB_ENV
          echo "CROWDIN_PERSONAL_TOKEN=${{ secrets.CROWDIN_PERSONAL_TOKEN }}" >> $GITHUB_ENV

      - name: Update Crowdin Contributors Table
        uses: andrii-bodnar/action-crowdin-contributors@v2.0.0
        with:
          contributors_per_line: 8
          max_contributors: 32
          image_size: 50
          min_words_contributed: 256
          include_languages: true
          files: docs/CROWDIN_CONTRIBUTORS.md
```

</details>

But it failed with the following error message:

<details><summary>Click to expand the error message</summary>

```
##[debug]Evaluating condition for step: 'Update Crowdin Contributors Table'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Update Crowdin Contributors Table
##[debug]Loading inputs
##[debug]Loading env
Run andrii-bodnar/action-crowdin-contributors@v[2](https://github.com/hwhsu1231/cmake-docs-l10n-draft5/actions/runs/9234314328/job/25407894079#step:6:2).0.0
  with:
    contributors_per_line: 8
    max_contributors: [3](https://github.com/hwhsu1231/cmake-docs-l10n-draft5/actions/runs/9234314328/job/25407894079#step:6:3)2
    image_size: 50
    min_words_contributed: 2[5](https://github.com/hwhsu1231/cmake-docs-l10n-draft5/actions/runs/9234314328/job/25407894079#step:6:5)6
    include_languages: true
    files: docs/CROWDIN_CONTRIBUTORS.md
    placeholder_start: <!-- CROWDIN-CONTRIBUTORS-START -->
    placeholder_end: <!-- CROWDIN-CONTRIBUTORS-END -->
  env:
    CROWDIN_PROJECT_ID: 8
    CROWDIN_ORGANIZATION: https://org-test.api.crowdin.com
    CROWDIN_PERSONAL_TOKEN: ***
::add-mask::***
::add-mask::***
Validating files...
Downloading the report...
Error: Cannot generate report. Message: CrowdinError: getaddrinfo EAI_AGAIN https
    at handleHttpClientError (/home/runner/work/_actions/andrii-bodnar/action-crowdin-contributors/v2.0.0/node_modules/@crowdin/crowdin-api-client/out/core/index.js:[7](https://github.com/hwhsu1231/cmake-docs-l10n-draft5/actions/runs/9234314328/job/25407894079#step:6:7)5:1)
    at /home/runner/work/_actions/andrii-bodnar/action-crowdin-contributors/v2.0.0/node_modules/@crowdin/crowdin-api-client/out/core/index.js:235:1
    at processTicksAndRejections (node:internal/process/task_queues:[9](https://github.com/hwhsu1231/cmake-docs-l10n-draft5/actions/runs/9234314328/job/25407894079#step:6:9)5:5) {
  [stack]: 'Error: getaddrinfo EAI_AGAIN https\n' +
    '    at handleHttpClientError (/home/runner/work/_actions/andrii-bodnar/action-crowdin-contributors/v2.0.0/node_modules/@crowdin/crowdin-api-client/out/core/index.js:75:1)\n' +
    '    at /home/runner/work/_actions/andrii-bodnar/action-crowdin-contributors/v2.0.0/node_modules/@crowdin/crowdin-api-client/out/core/index.js:235:1\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)',
  [message]: 'getaddrinfo EAI_AGAIN https',
  code: 500
}
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Update Crowdin Contributors Table
```

</details>

What happened? What did I miss? Is this a bug?

BTW, I can download translations from the project in Crowdin Enterprise with crowdin-cli successfully.

### Versions

* action-crowdin-contributors: `v2.0.0`

**Comment by andrii-bodnar** [comment]
I just released [v3.0.0](https://github.com/andrii-bodnar/action-crowdin-contributors/releases/tag/v3.0.0), which is a major overhaul of the action. The e2e test runs on the Crowdin Enterprise organization, and everything is passing there with success.

Logs: https://github.com/andrii-bodnar/action-crowdin-contributors/actions/runs/20129072233/job/57765698479

I hope the issue is no longer relevant.

**Comment by andrii-bodnar** [comment]
@hwhsu1231 Thanks for the details! Could you try running the action in [debug mode](https://docs.github.com/en/actions/how-tos/monitor-workflows/enable-debug-logging)? That should provide more information about the error.

**Comment by andrii-bodnar** [comment]
@hwhsu1231 the problem was with the `CROWDIN_ORGANIZATION` value - the Action only expected `ltdorgtest`. I added flexible organization detection, so it should work with different formats now.
